`define BR_BUS_LEN 34
`define IF_to_ID_LEN 64
`define ID_to_EXE_LEN 163
`define RF_BUS_LEN 38
`define EXE_to_MEM_LEN 109
`define MEM_to_WB_LEN 103
`define EXE_RF_LEN 38
`define MEM_RF_LEN 38
`define WB_RF_LEN  38
`define DEST_LEN 5

`define ST_W 7
`define ST_B 6
`define ST_H 5
`define LD_W 4
`define LD_B 3
`define LD_H 2
`define LD_BU 1
`define LD_HU 0